apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promptfoo-pvc
  namespace: nosi-fusion-innovation-promptfoo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi