apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-promptfoo
  namespace: nosi-fusion-innovation-promptfoo
spec:
  selector:
    matchLabels:
      app: app-promptfoo
  template:
    metadata:
      labels:
        app: app-promptfoo
    spec:
      imagePullSecrets:
        - name: docker-nosinovacao
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ['sh', '-c', 'chown -R 100:100 /home/promptfoo/.promptfoo']
          resources:
            requests:
              memory: '200Mi'
              cpu: '100m'
          volumeMounts:
            - name: promptfoo-pvc
              mountPath: /home/promptfoo/.promptfoo
      containers:
        - name: app-promptfoo
          image: europe-west4-docker.pkg.dev/nos-ddplab-d-269916/docker-repo/ri-promptfoo:0.0.3
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
          env:
            - name: AZURE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: azureai-secrets
                  key: AZURE_API_KEY
            - name: AZURE_API_HOST
              valueFrom:
                secretKeyRef:
                  name: azureai-secrets
                  key: AZURE_API_HOST
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: googleai-secrets
                  key: GOOGLE_API_KEY
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_SECRET
            - name: AUTH0_ISSUER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_ISSUER_BASE_URL
            - name: AUTH0_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_BASE_URL
          volumeMounts:
            - name: promptfoo-pvc
              mountPath: /home/promptfoo/.promptfoo
      volumes:
        - name: promptfoo-pvc
          persistentVolumeClaim:
            claimName: promptfoo-pvc
